### ISSUE TITLE
Cannot setup Credential

### ISSUE THREAD

**Issue by imakou** [CannerCMS/cannercms#136]
Hi All,

I've generated cert from Firebase and saved with `canner.cloud.js` under the same folder.
I tried to access the cert.json as following
`default: [new FirebaseCredential(require('./cert.json'))]`
Then, I got the error message:

```
Reading canner.cloud.js occurs errors. Error: Unexpected token ;

It seems that you give a wrong path in your canner.cloud.js. Check out the links below to fix it.
```
I think there is nothing worng with my setting...

Any suggestion?

Thanks. 
![screen shot 2018-12-19 at 5 29 22 pm](https://user-images.githubusercontent.com/1507950/50252047-c45d7800-03b3-11e9-8bdb-22a941647797.png)
![screen shot 2018-12-19 at 5 29 43 pm](https://user-images.githubusercontent.com/1507950/50252048-c4f60e80-03b3-11e9-98f5-78653dce59d8.png)

**Comment by imakou** [comment]
In addition, always facing the error when tried to initialize the project

`EACCES: permission denied, mkdir '/snapshot/cli/dist/schema/company/components'`

I install @canner/Cli by yarn as global installing.

**Comment by abz53378** [comment]
Hi, @imakou  thanks for the report.

It's a typo in the company template, you can find this line:` pathname; 'about'`, and please change it to `pathname: 'about'` (`;` to `:`) in `canner.cloud.js`.

And I just released `2.7.9` which fixes both two problems, please try it, thanks!

**Comment by imakou** [comment]
Hi,

The bug is still there.
The same error when I tried to deploy the second time.
So, it only deploys successfully at the first time.
Please check the bug, I believe Canner has the potential to be a good tool.
