### ISSUE TITLE
Error: EACCES: permission denied, open '/Users/allen/.config/configstore/canner.json'

### ISSUE THREAD

**Issue by imakou** [CannerCMS/cannercms#139]
Hi,

Have tried #128 and ```sudo npm i -g @canner/cli```
But the error is still there. 
MAC OS 10.14
NODE: 10.15

Thanks.
```
(node:9057) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/Users/allen/.config/configstore/canner.json'
You don't have access to this file.

    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at e.exports.get all [as all] (/Users/allen/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:230:248906)
    at new e.exports (/Users/allen/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:230:248867)
    at T (/Users/allen/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:127:34900)
    at /Users/allen/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:127:35056
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:9057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @canner/cli@2.8.3
```

**Comment by abz53378** [comment]
Hi, Imakou, thanks for the question, I just found a solution for EACCESS error, try using `sudo npm i --unsafe-perm -g @canner/cli`, it will execute the CLI always as root role, see [here](https://stackoverflow.com/questions/49084929/npm-sudo-global-installation-unsafe-perm)

**Comment by imakou** [comment]
Hi @abz53378 ,
The cmd resolve the issue for instilling @canner/cli.
But,  I got another error msg ```EACCES: permission denied, open '/Users/username/.config/configstore/canner.json'```
I can still run the ```canner script:serve``` by typing ```sudo canner script:serve```.
I think that it's little weird. I faced this issue before. Maybe your team has to fix this problem?

thanks.

**Comment by imakou** [comment]
Hi,

I think that the cmd ```sudo npm i --unsafe-perm -g @canner/cli``` doest not work very well because the system asks root's permission every single time if I change the files(e.g. canner.cloud.js) created by Canner/cli. Should fix the issue and release a new version?

**Comment by imakou** [comment]
update:
The installation of @canner/cli@2.8.3 is working well in Windows 10, but MacOS and Docker container Node V10.x.

**Comment by abz53378** [comment]
Hi, Imakou, thanks for your tracking. We are focusing on resolving this issue, and I still have some questions.

1. After the solution of #128, do you have tried to install `@canner/cli` without `sudo`? I think it should work because you have changed the path of npm directory which didn't need root permission to read and write.
2. Could you paste your role by typing `whoami` in the terminal and the permissions of files in your project directory by typing `ls -l`, it should like this:
  ```
  $ siou@siour-iMac whoami
  $ siou
  $ siou@siour-iMac ls -l
  $ total 24
     -rw-r--r--   1 siou  staff  1548 Jan 22 11:00 canner.cloud.js
     -rw-r--r--   1 siou  staff   572 Jan 22 10:59 canner.schema.js
     drwxr-xr-x   3 siou  staff    96 Jan 22 10:59 components
     drwxr-xr-x  10 siou  staff   320 Jan 19 14:30 node_modules
     -rw-r--r--   1 siou  staff  2114 Jan 19 14:30 package-lock.json
     drwxr-xr-x   4 siou  staff   128 Jan 22 10:59 schema
  ```

Thanks!

Some great references: 
1.  [What-does-unsafe-perm-in-npm-actually-do](https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/)
2. [We strongly recommend using a Node version manager to install Node.js and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
3. [resolving-eacces-permissions-errors-when-installing-packages-globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

**Comment by imakou** [comment]
Hi @abz53378 ,
It shows errors by Installing @canner/cli without sudo.
```npm i --unsafe-perm -g @canner/cli``` and ```npm i -g @canner/cli``` cause the same error.
I've changed Node.js' folder already as follow instruction as #128

Canner is a good tool. I believe it has huge potential. But it has to be stable first.
That is the second time I encounter cli problem.  

Thanks.


```
npm WARN checkPermissions Missing write access to /Users/allen/.npm-global/lib/node_modules
npm ERR! path /Users/allen/.npm-global/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/allen/.npm-global/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/Users/allen/.npm-global/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/Users/allen/.npm-global/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/allen/.npm-global/lib/node_modules' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/allen/.npm/_logs/2019-01-23T04_21_33_531Z-debug.log
➜  Desktop who am i
allen    ttys008  Jan 22 23:20
```

**Comment by abz53378** [comment]
Hi, @imakou , thanks for your reply and advice, we will keep improving Canner.

And for the error above, I reproduced it and also resolved it, here are the conclusion. Hope this helps you.

### 1. Why `~/.npm-global` also needs the `root/Administrator` permission.
Basically, after following the #128, and **directly run** `npm i -g @canner/cli` without `sudo`, everything works fine. The two directory `~/.npm-global/bin` and `~/.npm-globa/lib` are created by me.
**before installing**
```
$ siou@siour-iMac ls -la ~/.npm-global
$ total 24
   drwxr-xr-x   2 siou  staff   64 Jan 23 14:58 .
   drwxr-xr-x+ 50 siou  staff 1600 Jan 23 14:58 ..

```

**after installing by `npm i -g @canner/cli`**
```
$ siou@siour-iMac ls -la ~/.npm-global
$ total 0
   drwxr-xr-x   4 siou  staff  128 Jan 23 15:01 .
   drwxr-xr-x+ 50 siou  staff 1600 Jan 23 15:07 ..
   drwxr-xr-x   3 siou  staff   96 Jan 23 15:01 bin
   drwxr-xr-x   3 siou  staff   96 Jan 23 15:01 lib
```


But if running `sudo npm i -g @canner/cli` first (while the `.npm-gloabl` is still empty), it will causes `~/.npm-global/lib` and `~/.npm-global` are actually created by the `root` since the `sudo` command. 
And also I got the familiar error(we discussed at above comments) in this step.

**after installing by `sudo npm -g @canner/cli`**
```
$siou@siour-iMac sudo npm i -g @canner/cli                                                                                               
Password:
/Users/siou/.npm-global/bin/canner -> /Users/siou/.npm-global/lib/node_modules/@canner/cli/download/dist/cli

> @canner/cli@2.8.3 postinstall /Users/siou/.npm-global/lib/node_modules/@canner/cli
> node download/install.js

(node:42800) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/Users/siou/.config/configstore/canner.json'
You don't have access to this file.

    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at e.exports.get all [as all] (/Users/siou/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:230:248906)
    at new e.exports (/Users/siou/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:230:248867)
    at T (/Users/siou/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:127:34900)
    at /Users/siou/.npm-global/lib/node_modules/@canner/cli/download/dist/download.js:127:35056
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:42800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:42800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @canner/cli@2.8.3
added 64 packages from 68 contributors in 14.418s
```

```
$ siou@siour-iMac ls -la ~/.npm-global
$ total 0
   drwxr-xr-x   4 siou  staff  128 Jan 23 15:09 .
   drwxr-xr-x+ 50 siou  staff 1600 Jan 23 15:11 ..
   drwxr-xr-x   3 root  staff   96 Jan 23 15:09 bin
   drwxr-xr-x   3 root  staff   96 Jan 23 15:09 lib
```

So after that, if we try to install `@canner/cli` without `sudo`, it will always say `permission denied about accessing '~/.npm-global/lib'` which you mentioned at the last comment.

### 2. How to resolve it
So, the problem here is just the ownership of `~/.npm-global/lib` and `~/.npm-global/bin` should be `siou`, not `root`. and we can simply change it by the command ``sudo chown -R `whomai`~/.npm-global ``

```
$ siou@siour-iMac sudo chown -R `whoami` ~/.npm-global
$ siou@siour-iMac ls -la ~/.npm-global
$ total 0
   drwxr-xr-x   4 siou  staff  128 Jan 23 15:09 .
   drwxr-xr-x+ 50 siou  staff 1600 Jan 23 15:11 ..
   drwxr-xr-x   3 siou  staff   96 Jan 23 15:09 bin
   drwxr-xr-x   3 siou  staff   96 Jan 23 15:09 lib
```

And then, I can reinstall it with the command `npm i -g @canner/cli` again without any error.

Hope this helps you, and if there is any result is different from yours, please let us know. Thanks!

**Comment by abz53378** [comment]
Also, you have to ensure the files in the project have the correct ownership. I guess they may be changed because of the previous wrong installed `@canner/cli`

**Comment by imakou** [comment]
Hi @abz53378,
@Canner/cli works very well by following your instruction ``` sudo chown -R `whoami` ~/.npm-global```.

Now, I'm a happy developer!! ❤️
